### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by jren2017** [izharikov/state-farm-distracted-driver-detection#1]
Traceback (most recent call last):
  File "/home/administrator/Applications/pycharm-2018.1/helpers/pydev/pydev_run_in_console.py", line 53, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
PyDev console: starting.
  File "/home/administrator/Applications/pycharm-2018.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
  File "/home/administrator/workingspace/workingprojects/kaggle/state-farm-distracted-driver-detection/src/train.py", line 66, in <module>
    generator=generator, dyn_lr=dyn_lr, initial_epoch=initial_epoch)
  File "/home/administrator/workingspace/workingprojects/kaggle/state-farm-distracted-driver-detection/src/train.py", line 13, in train
    model = get_model(model_type, img_width, print_summary=print_summary, fc_layers=fc_layers, dropout=dropout)
  File "/home/administrator/workingspace/workingprojects/kaggle/state-farm-distracted-driver-detection/src/models/__init__.py", line 10, in get_model
    return vgg19.get_model(print_summary, img_width, fc_layers, dropout)
  File "/home/administrator/workingspace/workingprojects/kaggle/state-farm-distracted-driver-detection/src/models/vgg19.py", line 24, in get_model
    x = add_fc_layers(x, fc_layers, fc_dropout_layers)
  File "/home/administrator/workingspace/workingprojects/kaggle/state-farm-distracted-driver-detection/src/models/fc_layers.py", line 8, in add_fc_layers
    dropout = fc_dropout_layers[i]
TypeError: 'NoneType' object is not subscriptable

Hello, when i ran this code, I met the above problem? Could you help give some instruction?
which version of tensorflow, keras are you using?

**Comment by izharikov** [comment]
@jren2017, could you please share command with which you started file `train.py`? 
Also, make note, that this repo is not for LTS or contributing, it's just share the code, written by me for diploma.

**Comment by jren2017** [comment]
Thanks your reply!
I used the Pycharm to debug the code:
python train.py --model vgg16 --width 224 --optimizer adam --lr 1e-5 --batch 16 --epochs 50
python train.py --model vgg19 --width 224 --optimizer adam --lr 1e-5 --batch 16 --epochs 50

when i run both above two commands, the problem will happen.

**Comment by izharikov** [comment]
Hope, answer is in [this comment](https://github.com/izharikov/state-farm-distracted-driver-detection/issues/2#issuecomment-384902953)
