### ISSUE TITLE
error for simple model

### ISSUE THREAD

**Issue by jren2017** [izharikov/state-farm-distracted-driver-detection#2]
```
1140/1144 [============================>.] - ETA: 3s - loss: 2.2472 - acc: 0.1638
1141/1144 [============================>.] - ETA: 2s - loss: 2.2471 - acc: 0.1639
1142/1144 [============================>.] - ETA: 1s - loss: 2.2470 - acc: 0.1639
1143/1144 [============================>.] - ETA: 0s - loss: 2.2470 - acc: 0.1638Traceback (most recent call last):
  File "/home/administrator/workingspace/workingprojects/kaggle/.venv/lib/python3.5/site-packages/keras/utils/data_utils.py", line 578, in get
    inputs = self.queue.get(block=True).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/administrator/workingspace/workingprojects/kaggle/.venv/lib/python3.5/site-packages/keras/utils/data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "/home/administrator/workingspace/workingprojects/kaggle/.venv/lib/python3.5/site-packages/keras/preprocessing/image.py", line 1034, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)
  File "/home/administrator/workingspace/workingprojects/kaggle/.venv/lib/python3.5/site-packages/keras/preprocessing/image.py", line 1441, in _get_batches_of_transformed_samples
    x = self.image_data_generator.standardize(x)
  File "/home/administrator/workingspace/workingprojects/kaggle/.venv/lib/python3.5/site-packages/keras/preprocessing/image.py", line 797, in standardize
    x -= self.mean
ValueError: operands could not be broadcast together with shapes (224,224,3) (3,1,1) (224,224,3) 
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/administrator/Applications/pycharm-2018.1/helpers/pydev/pydev_run_in_console.py", line 53, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/administrator/Applications/pycharm-2018.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/administrator/workingspace/workingprojects/kaggle/state-farm-distracted-driver-detection/src/train.py", line 66, in <module>
    generator=generator, dyn_lr=dyn_lr, initial_epoch=initial_epoch)
  File "/home/administrator/workingspace/workingprojects/kaggle/state-farm-distracted-driver-detection/src/train.py", line 41, in train
    initial_epoch=initial_epoch)
  File "/home/administrator/workingspace/workingprojects/kaggle/.venv/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/administrator/workingspace/workingprojects/kaggle/.venv/lib/python3.5/site-packages/keras/models.py", line 1315, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/administrator/workingspace/workingprojects/kaggle/.venv/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/administrator/workingspace/workingprojects/kaggle/.venv/lib/python3.5/site-packages/keras/engine/training.py", line 2250, in fit_generator
    max_queue_size=max_queue_size)
  File "/home/administrator/workingspace/workingprojects/kaggle/.venv/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/administrator/workingspace/workingprojects/kaggle/.venv/lib/python3.5/site-packages/keras/engine/training.py", line 2383, in evaluate_generator
    generator_output = next(output_generator)
  File "/home/administrator/workingspace/workingprojects/kaggle/.venv/lib/python3.5/site-packages/keras/utils/data_utils.py", line 584, in get
    six.raise_from(StopIteration(e), e)
  File "<string>", line 3, in raise_from
StopIteration: operands could not be broadcast together with shapes (224,224,3) (3,1,1) (224,224,3) 
PyDev console: starting.
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
```
How to fix this??

**Comment by izharikov** [comment]
@jren2017 , here I also the command line args, passed to the script. And if to be hones, this `simple_model` doesn't make any progress in training (I mean, that acc is too low and val_los is very big), so you could skip this and use fine-tuning  using others models. My current best results we achieved using `xception` model, where I'd achived kaggle score between 0.3-0.5 (depends on params of train process).

**Comment by jren2017** [comment]
Here I noticed the problem when the training is near to the end of the first epoch:

File "", line 3, in raise_from
StopIteration: operands could not be broadcast together with shapes (224,224,3) (3,1,1) (224,224,3)

I'm wondering is there any problem about the code? I will continue debug it. 
Could you share your diploma thesis, I want to learn more about this application.

**Comment by izharikov** [comment]
@jren2017 , so, I could help you, but I really need command arguments, that you passed to script.
My diploma is currently in progress (teoretical part) and I could share, but it'll be in Russian, so if you know russian, I're welcom :grinning:

**Comment by jren2017** [comment]
![image](https://user-images.githubusercontent.com/24396551/39327570-8843523a-49ec-11e8-9a71-1c61a287f326.png)

This command argumets are shown in the above picture.

can you give me your email, we can communicate via email, thanks your help.

**Comment by jren2017** [comment]
Following pictures may give more information, the problem is about the data generator for the train?
![image](https://user-images.githubusercontent.com/24396551/39344700-18207c7a-4a38-11e8-9f0b-b75802b780de.png)

![image](https://user-images.githubusercontent.com/24396551/39344703-1e19bb6e-4a38-11e8-875b-d3304e2c3209.png)


I still have not solve this problem, hope you can help

**Comment by izharikov** [comment]
@jren2017, I've fixed the issue with vgg train in the  commit dc4f420. Also, my suggestion is to use `--generator custom` param in the train process, as it generates train and validation dataset on different drivers.
Hope `--generator custom` will fix the issue with the last batch.
Also, my email is zharikovigor97@gmail.com. Feel free to ask questions, I'll response to you as soon as possible.

**Note**. For `xception` model better to use 299 img width.
